# Generated by Django 2.2 on 2019-04-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='地址')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
            ],
            options={
                'verbose_name': '黑单',
                'verbose_name_plural': '黑单',
                'ordering': ['createtime'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
                ('nickname', models.CharField(max_length=20, verbose_name='匿名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['createtime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.URLField(verbose_name='头像')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(max_length=256, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='昵称')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('ipaddr', models.GenericIPAddressField(null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['createtime'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='正文')),
                ('attachment', models.TextField(null=True, verbose_name='附件')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='标题')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('commentnum', models.IntegerField(default=0, verbose_name='评论')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devproject.User', verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devproject.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '线程',
                'verbose_name_plural': '线程',
                'ordering': ['createtime'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.TextField(null=True, verbose_name='附件')),
                ('body', models.TextField(default='', verbose_name='正文')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='标题')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devproject.User', verbose_name='作者')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devproject.Thread', verbose_name='线程')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['createtime'],
            },
        ),
    ]
