# Generated by Django 2.2 on 2019-04-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='musicurl',
            field=models.CharField(max_length=300, null=True, verbose_name='音乐'),
        ),
        migrations.AddField(
            model_name='thread',
            name='musicurl',
            field=models.CharField(max_length=300, null=True, verbose_name='音乐'),
        ),
    ]
