# Generated by Django 2.2 on 2019-04-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0002_thread_lastthreadid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='lastthreadid',
        ),
    ]
