# Generated by Django 2.2 on 2019-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0002_auto_20190406_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='musicurl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='音乐'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='musicurl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='音乐'),
        ),
    ]
