# Generated by Django 2.1.7 on 2019-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0003_auto_20190406_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastpublishtime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.TextField(blank=True, null=True, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='attachment',
            field=models.TextField(blank=True, null=True, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
    ]
