# Generated by Django 2.2 on 2019-04-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0003_remove_thread_lastthreadid'),
        ('devproject', '0004_auto_20190407_2320'),
    ]

    operations = [
    ]
