# Generated by Django 2.2 on 2019-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devproject', '0005_merge_20190413_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
